FROM osixia/openldap:1.1.9
MAINTAINER Orangehrm <thulana@orangehrm.us.com>
#Install dependent software
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y  --no-install-recommends --force-yes \
  curl \
  wget
ADD bootstrap /container/service/slapd/assets/config/bootstrap
ADD certs /container/service/slapd/assets/certs
ADD environment /container/environment/01-custom